
import { Specialty, CountryCode, Company } from './types';

export interface CountryConfig {
  name: string;
  flag: string;
  currency: string;
  locale: string;
  taxLabels: {
    vat: string;
    income: string;
    social: string;
    idNumber: string;
  };
  defaultRates: {
    vat: number;
    income: number;
    social: number;
  };
  translations: Record<string, any>;
}

const COMMON_PT = {
  save: 'Guardar Alterações',
  cancel: 'Cancelar',
  export: 'Exportar PDF',
  delete: 'Eliminar',
  edit: 'Editar',
  add: 'Adicionar',
  back: 'Voltar',
  next: 'Próximo',
  finish: 'Concluir',
  loading: 'A carregar...',
  confirm: 'Confirmar',
  status: 'Estado do Orçamento',
  date: 'Data',
  total: 'Total',
  action: 'Ação',
  name: 'Nome',
  email: 'E-mail',
  phone: 'Telefone',
  address: 'Morada',
  nif: 'NIF/NIPC',
  password: 'Palavra-passe',
  companyName: 'Nome da Empresa',
  specialties: 'Especialidades',
  description: 'Descrição',
  quantity: 'Qtd',
  unit: 'Un.',
  price: 'Preço',
  subtotal: 'Subtotal',
  balance: 'Saldo em Aberto',
  paid: 'Pago',
  pending: 'Pendente',
  approved: 'Aprovado',
  rejected: 'Rejeitado',
  draft: 'Pendente',
  limitReached: 'Limite Atingido',
  upgradeNow: 'Fazer Upgrade',
  usageBudgets: 'Orçamentos Utilizados',
  limitSpecialties: 'Limite de 2 especialidades no plano gratuito.',
  limitBudgetItemsSpecialties: 'No plano gratuito, o orçamento só pode conter 2 especialidades diferentes.',
  limitDuplicateSpecialty: 'No plano gratuito, cada especialidade só pode ser usada uma vez por orçamento.',
  contactPerson: 'Nome do Contacto',
  renewalAlert: 'A sua assinatura mensal expira em {days} dias. Renove agora para evitar a interrupção dos seus serviços!',
  notifications: {
    title: 'Notificações',
    empty: 'Não tem novas notificações.',
    markAllRead: 'Marcar todas como lidas',
    sendTitle: 'Centro de Disparo Master',
    sendBtn: 'Enviar Notificação',
    targetAll: 'Todos os Utilizadores',
    targetPremium: 'Apenas Premium',
    targetFree: 'Apenas Plano Básico',
    retentionTitle: 'Aviso de Retenção Premium',
    retentionMsg: 'Atenção! A sua subscrição Premium garante orçamentos ilimitados e gestão total de custos. Não cancele para manter a sua produtividade máxima!',
    autoLabel: 'Mensagem Automática'
  },
  hub: {
    summary: 'Resumo',
    info: 'Orçamento',
    payments: 'Pagamentos',
    expenses: 'Custos da Obra',
    back: 'Voltar',
    welcome: 'Bem-vindo à Átrio',
    loadingEnv: 'A carregar o seu ambiente de trabalho...',
    configuring: 'Configurando o seu portal profissional...'
  },
  projectDashboard: {
    title: 'Resumo do Projeto',
    financialHealth: 'Saúde Financeira',
    revenue: 'Receita Total',
    expenses: 'Custos Totais',
    profit: 'Lucro Real',
    margin: 'Margem',
    collected: 'Já Recebido',
    toCollect: 'Falta Receber',
    comparison: 'Receita vs Custos',
    paymentStatus: 'Estado de Recebimento'
  },
  expenses: {
    title: 'Gestão de Custos',
    subtitle: 'Registe e controle os gastos reais de cada obra.',
    addItem: 'Adicionar Gasto',
    itemDescription: 'Item / Material',
    unit: 'Unidade',
    qty: 'Qtd',
    price: 'Preço Unit.',
    totalItem: 'Total Item',
    totalExpenses: 'Total de Custos',
    profit: 'Lucro Previsto',
    limitFree: 'No plano gratuito, pode gerir custos de apenas 3 projetos aprovados.',
    noExpenses: 'Ainda não registou gastos para este projeto.'
  },
  payments: {
    title: 'Gestão Financeira',
    subtitle: 'Controle os recebimentos e saldos dos seus projetos.',
    addPayment: 'Registar Pagamento',
    amount: 'Valor Recebido',
    paymentDate: 'Data do Pagamento',
    proof: 'Comprovativo (Upload)',
    history: 'Histórico de Recebimentos',
    noPayments: 'Nenhum pagamento registado para este projeto.',
    totalBudget: 'Total do Projeto',
    remaining: 'Falta Receber',
    viewProof: 'Ver Comprovativo',
    success: 'Pagamento registado com sucesso!',
    onlyApproved: 'Apenas orçamentos aprovados podem receber pagamentos.',
    limitFree: 'No plano gratuito, pode gerir pagamentos de apenas 3 projetos aprovados.'
  },
  auth: {
    loginTitle: 'Entrar na Área',
    loginSub: 'Aceda ao seu painel de orçamentos ÁTRIO.',
    registerTitle: 'Criar conta SaaS',
    registerSub: 'Junte-se a centenas de empresas.',
    verifyTitle: 'Código Enviado',
    verifySub: 'Verifique o seu email.',
    btnEnter: 'Entrar Agora',
    btnRegister: 'Criar Plataforma',
    btnVerify: 'Ativar Conta',
    switchRegister: 'Novo na plataforma? Crie a sua conta',
    switchLogin: 'Já possui acesso? Faça login',
    benefit1: 'PDFs Estruturados',
    benefit1Desc: 'Exportação profissional com 1 clique.',
    benefit2: 'Relatórios PRO',
    benefit2Desc: 'Análise de lucro e conversão real.',
    benefit3: 'Gestão Financeira',
    benefit3Desc: 'Controlo total de pagamentos.',
    benefit4: 'Taxas Automáticas',
    benefit4Desc: 'Impostos locais adaptados.',
    benefit5: 'Histórico Central',
    benefit5Desc: 'CRM integrado para clientes.',
    benefit6: 'SaaS Global',
    benefit6Desc: 'Acesso em 7 países simultâneos.'
  },
  sidebar: {
    dashboard: 'Painel Geral',
    analytics: 'Análises PRO',
    newBudget: 'Novo Orçamento',
    payments: 'Pagamentos',
    expenses: 'Custos da Obra',
    settings: 'Configurações',
    subscription: 'Assinatura',
    logout: 'Terminar Sessão'
  },
  dashboard: {
    totalPaid: 'Total Recebido',
    approvedVal: 'Aprovados',
    pendingVal: 'Pendentes',
    tableRef: 'Referência / Cliente',
    activeSpecialties: 'Especialidades Ativas',
    specialtiesSub: 'Setores em que a sua empresa atua neste momento.',
    recentActivity: 'Atividade Recente',
    noBudgets: 'Ainda não emitiu orçamentos.',
    createFirst: 'Crie o seu primeiro orçamento profissional agora.'
  },
  analytics: {
    title: 'Análises de Negócio PRO',
    subtitle: 'Transforme os seus orçamentos em dados valiosos.',
    upgradeBtn: 'ATUALIZAR PARA PREMIUM',
    revenueApproved: 'Receita Total',
    totalCosts: 'Custos Totais',
    netProfit: 'Lucro Líquido',
    pipelinePending: 'Pipeline Pendente',
    conversionRate: 'Taxa de Conversão',
    distributionStatus: 'Distribuição por Estado',
    revenueBySpecialty: 'Receita por Especialidade',
    profitBySpecialty: 'Lucro por Especialidade',
    note: 'As análises acima consideram todos os orçamentos históricos da empresa.',
    benefit1Title: 'Distribuição',
    benefit1Desc: 'Saiba o estado dos seus projetos.',
    benefit2Title: 'Receita por Categoria',
    benefit2Desc: 'Identifique serviços rentáveis.',
    benefit3Title: 'Aprovação',
    benefit3Desc: 'Mensure a eficácia das propostas.'
  },
  subscription: {
    currentPlan: 'Plano Atual',
    renewsOn: 'A sua subscrição renova em',
    upgradeBtn: 'Upgrade para Premium',
    plansTitle: 'Planos Disponíveis',
    historyTitle: 'Histórico e Faturação',
    paymentMethod: 'Método de Pagamento',
    basicName: 'Básico',
    proName: 'Profissional',
    freePrice: '0€/mês',
    proPrice: '9,90€/mês',
    proTaxInfo: '+ IVA (Total 12,18€)',
    activePlan: 'Plano Ativo',
    selectPlan: 'Selecionar Plano',
    emptyHistory: 'Sem histórico de faturação',
    emptyHistoryDesc: 'Faça o upgrade para receber faturas.',
    changeMethod: 'Alterar',
    checkoutTitle: 'Checkout ÁTRIO Premium',
    processing: 'A processar pagamento...',
    payNow: 'Pagar Agora',
    features: {
      budgets3: '3 Orçamentos Mensais',
      budgetsInf: 'Orçamentos Ilimitados',
      pdfExport: 'Exportação PDF Profissional',
      payments: 'Gestão de Pagamentos',
      analytics: 'Análises Financeiras PRO'
    }
  },
  editor: {
    clientTitle: 'Dados do Cliente',
    itemsTitle: 'Itens do Serviço',
    totalsTitle: 'Totais e Impostos',
    validUntil: 'Validade do Orçamento',
    notes: 'Notas do Orçamento',
    paymentTerms: 'Condições de pagamento locais aplicadas.'
  },
  specialtyNames: {
    [Specialty.Pedreiro]: 'Pedreiro',
    [Specialty.Canalizador]: 'Canalizador',
    [Specialty.Eletricista]: 'Eletricista',
    [Specialty.Pladur]: 'Pladur',
    [Specialty.Capoto]: 'Capoto',
    [Specialty.Pintura]: 'Pintura',
    [Specialty.Carpinteiro]: 'Carpinteiro',
    [Specialty.Estuque]: 'Estuque',
    [Specialty.Outro]: 'Outro'
  }
};

export const COUNTRY_CONFIGS: Record<CountryCode, CountryConfig> = {
  PT: {
    name: 'Portugal',
    flag: '🇵🇹',
    currency: 'EUR',
    locale: 'pt-PT',
    taxLabels: { vat: 'IVA', income: 'IRS', social: 'Seg. Social', idNumber: 'NIF' },
    defaultRates: { vat: 23, income: 25, social: 21.4 },
    translations: COMMON_PT
  },
  BR: {
    name: 'Brasil',
    flag: '🇧🇷',
    currency: 'BRL',
    locale: 'pt-BR',
    taxLabels: { vat: 'ISS/ICMS', income: 'IRPJ', social: 'INSS', idNumber: 'CNPJ/CPF' },
    defaultRates: { vat: 18, income: 15, social: 11 },
    translations: {
      ...COMMON_PT,
      save: 'Salvar Alterações',
      address: 'Endereço',
      nif: 'CNPJ/CPF',
      contactPerson: 'Nome do Contato',
      renewalAlert: 'Sua assinatura mensal expira em {days} dias. Renove agora para evitar a interrupção dos seus serviços!',
      hub: {
        ...COMMON_PT.hub,
        expenses: 'Custos da Obra'
      },
      auth: { ...COMMON_PT.auth, loginTitle: 'Acessar Painel', registerTitle: 'Criar Plataforma SaaS' },
      analytics: { ...COMMON_PT.analytics, title: 'Análises de Negócio PRO', subtitle: 'Transforme seus orçamentos em dados.' },
      subscription: { ...COMMON_PT.subscription, proPrice: 'R$ 49,90/mês', proTaxInfo: 'Taxas incluídas' },
      dashboard: { ...COMMON_PT.dashboard, specialtiesSub: 'Setores em que sua empresa atua no momento.' }
    }
  },
  ES: {
    name: 'Espanha',
    flag: '🇪🇸',
    currency: 'EUR',
    locale: 'es-ES',
    taxLabels: { vat: 'IVA', income: 'IRPF', social: 'Autónomos', idNumber: 'NIE/NIF' },
    defaultRates: { vat: 21, income: 19, social: 31 },
    translations: {
      ...COMMON_PT,
      save: 'Guardar Cambios',
      cancel: 'Cancelar',
      export: 'Exportar PDF',
      delete: 'Eliminar',
      edit: 'Editar',
      add: 'Añadir',
      back: 'Volver',
      next: 'Siguiente',
      finish: 'Finalizar',
      loading: 'Cargando...',
      confirm: 'Confirmar',
      status: 'Estado del Presupuesto',
      date: 'Fecha',
      total: 'Total',
      action: 'Acción',
      name: 'Nombre',
      email: 'Email',
      phone: 'Teléfono',
      address: 'Dirección',
      nif: 'NIF/NIE',
      contactPerson: 'Persona de contacto',
      password: 'Contraseña',
      companyName: 'Nombre de Empresa',
      specialties: 'Especialidades',
      description: 'Descripción',
      quantity: 'Cant.',
      unit: 'Un.',
      price: 'Precio',
      subtotal: 'Subtotal',
      balance: 'Saldo Pendiente',
      paid: 'Pagado',
      pending: 'Pendiente',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      draft: 'Pendiente',
      renewalAlert: 'Tu suscripción mensual expira en {days} días. ¡Renueva ahora para evitar la interrupción de tus servicios!',
      hub: {
        summary: 'Resumen',
        info: 'Presupuesto',
        payments: 'Pagos',
        expenses: 'Costes de Obra',
        back: 'Volver',
        welcome: 'Bienvenido a Átrio',
        loadingEnv: 'Cargando su espacio de trabalho...',
        configuring: 'Configurando su portal profesional...'
      },
      auth: {
        loginTitle: 'Acceder al Área',
        loginSub: 'Acceda a su panel de presupuestos ÁTRIO.',
        registerTitle: 'Crear conta SaaS',
        registerSub: 'Únase a cientos de empresas.',
        verifyTitle: 'Código Enviado',
        verifySub: 'Verifique su correo electrónico.',
        btnEnter: 'Entrar Ahora',
        btnRegister: 'Criar Plataforma',
        btnVerify: 'Activar Conta',
        switchRegister: '¿Nuevo? Cree su cuenta',
        switchLogin: '¿Ya tiene acceso? Entre aquí',
        benefit1: 'PDFs Estructurados',
        benefit1Desc: 'Exportación profesional con 1 clic.',
        benefit2: 'Informes PRO',
        benefit2Desc: 'Análisis de lucro y conversión real.',
        benefit3: 'Gestão Financeira',
        benefit3Desc: 'Control total de cobros.',
        benefit4: 'Impuestos Automáticos',
        benefit4Desc: 'Fiscalidad local adaptada.',
        benefit5: 'Historial Central',
        benefit5Desc: 'CRM integrado para clientes.',
        benefit6: 'SaaS Global',
        benefit6Desc: 'Acceso en 7 países.'
      },
      sidebar: {
        dashboard: 'Panel General',
        analytics: 'Análisis PRO',
        newBudget: 'Nuevo Presupuesto',
        settings: 'Ajustes',
        subscription: 'Suscripción',
        logout: 'Cerrar Sesión'
      },
      dashboard: {
        totalPaid: 'Total Recibido',
        approvedVal: 'Aprobados',
        pendingVal: 'Pendentes',
        tableRef: 'Referencia / Cliente',
        activeSpecialties: 'Especialidades Activas',
        specialtiesSub: 'Sectores en los que su empresa opera.',
        recentActivity: 'Atividade Recente',
        noBudgets: 'Aún no ha emitido presupuestos.',
        createFirst: 'Cree su primer presupuesto profesional ahora.'
      },
      analytics: {
        title: 'Análisis de Negocio PRO',
        subtitle: 'Transforme sus presupuestos en datos valiosos.',
        upgradeBtn: 'ACTUALIZAR A PREMIUM',
        revenueApproved: 'Ingresos Aprobados',
        pipelinePending: 'Pipeline Pendente',
        conversionRate: 'Tasa de Conversión',
        distributionStatus: 'Distribución por Estado',
        revenueBySpecialty: 'Valor por Especialidad',
        note: 'Los análisis anteriores consideran todos los presupuestos históricos.',
        benefit1Title: 'Distribución',
        benefit1Desc: 'Estado de sus proyectos.',
        benefit2Title: 'Ingresos por Categoría',
        benefit2Desc: 'Servicios rentables.',
        benefit3Title: 'Aprobación',
        benefit3Desc: 'Eficacia de las propuestas.'
      },
      subscription: {
        currentPlan: 'Plan Actual',
        renewsOn: 'Su suscripción se renueva el',
        upgradeBtn: 'Upgrade a Premium',
        plansTitle: 'Planes Disponibles',
        historyTitle: 'Historial y Facturación',
        paymentMethod: 'Método de Pago',
        basicName: 'Basico',
        proName: 'Profesional',
        freePrice: '0€/mes',
        proPrice: '9,90€/mes',
        proTaxInfo: '+ IVA (Total 12,18€)',
        activePlan: 'Plan Ativo',
        selectPlan: 'Seleccionar Plan',
        emptyHistory: 'Sin historial de faturação',
        emptyHistoryDesc: 'Actualice para receber facturas.',
        changeMethod: 'Cambiar',
        checkoutTitle: 'Checkout ÁTRIO Premium',
        processing: 'Procesando pago...',
        payNow: 'Pagar Ahora',
        features: {
          budgets3: '3 Presupuestos Mensuales',
          budgetsInf: 'Unlimitados',
          pdfExport: 'Exportación PDF Prof.',
          payments: 'Gestión de Cobros',
          analytics: 'Análisis Financieros PRO'
        }
      },
      editor: {
        clientTitle: 'Datos del Cliente',
        itemsTitle: 'Líneas de Serviço',
        totalsTitle: 'Totales e Impuestos',
        validUntil: 'Validez del presupuesto',
        notes: 'Notas del Presupuesto',
        paymentTerms: 'Condiciones de pago locales aplicadas.'
      },
      specialtyNames: {
        [Specialty.Pedreiro]: 'Albañil',
        [Specialty.Canalizador]: 'Fontanero',
        [Specialty.Eletricista]: 'Electricista',
        [Specialty.Pladur]: 'Pladur',
        [Specialty.Capoto]: 'Fachadas',
        [Specialty.Pintura]: 'Pintor',
        [Specialty.Carpinteiro]: 'Carpintero',
        [Specialty.Estuque]: 'Yesero',
        [Specialty.Outro]: 'Otros'
      }
    }
  },
  DE: {
    name: 'Alemanha',
    flag: '🇩🇪',
    currency: 'EUR',
    locale: 'de-DE',
    taxLabels: { vat: 'MwSt', income: 'Einkommensteuer', social: 'Sozialabgaben', idNumber: 'Steuernummer' },
    defaultRates: { vat: 19, income: 45, social: 20 },
    translations: {
      ...COMMON_PT,
      save: 'Speichern',
      cancel: 'Abbrechen',
      export: 'PDF Exportieren',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      add: 'Hinzufügen',
      back: 'Zurück',
      next: 'Weiter',
      finish: 'Fertigstellen',
      loading: 'Laden...',
      confirm: 'Bestätigen',
      status: 'Angebotsstatus',
      date: 'Datum',
      total: 'Gesamt',
      action: 'Ação',
      name: 'Name',
      email: 'E-Mail',
      phone: 'Telefon',
      address: 'Adresse',
      nif: 'Steuernummer',
      contactPerson: 'Kontaktperson',
      password: 'Passwort',
      companyName: 'Firmenname',
      specialties: 'Spezialgebiete',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einh.',
      price: 'Preis',
      subtotal: 'Zwischensumme',
      balance: 'Offener Betrag',
      paid: 'Bezahlt',
      pending: 'Ausstehend',
      approved: 'Bestätigt',
      rejected: 'Abgelehnt',
      draft: 'Ausstehend',
      renewalAlert: 'Ihr monatliches Abonnement läuft in {days} Tagen ab. Jetzt verlängern, um Dienstunterbrechungen zu vermeiden!',
      hub: {
        summary: 'Übersicht',
        info: 'Angebot',
        payments: 'Zahlungen',
        expenses: 'Projektkosten',
        back: 'Zurück',
        welcome: 'Willkommen bei Átrio',
        loadingEnv: 'Ihr Arbeitsbereich wird geladen...',
        configuring: 'Ihr professionelles Portal wird konfiguriert...'
      },
      auth: {
        loginTitle: 'Anmelden',
        loginSub: 'Greifen Sie auf Ihr ÁTRIO-Dashboard zu.',
        registerTitle: 'SaaS-Konto erstellen',
        registerSub: 'Schließen Sie sich Hunderten von Firmen an.',
        verifyTitle: 'Code gesendet',
        verifySub: 'Prüfen Sie Ihre E-Mails.',
        btnEnter: 'Jetzt anmelden',
        btnRegister: 'Plattform erstellen',
        btnVerify: 'Konto aktivieren',
        switchRegister: 'Neu hier? Konto erstellen',
        switchLogin: 'Bereits Mitglied? Hier anmelden',
        benefit1: 'Strukturierte PDFs',
        benefit1Desc: 'Professioneller Export mit 1 Klick.',
        benefit2: 'PRO Berichte',
        benefit2Desc: 'Gewinn- und Konversionsanalyse.',
        benefit3: 'Finanzmanagement',
        benefit3Desc: 'Vollständige Zahlungskontrolle.',
        benefit4: 'Autom. Steuern',
        benefit4Desc: 'Lokale Steuersätze angepasst.',
        benefit5: 'Zentraler Verlauf',
        benefit5Desc: 'Integriertes CRM für Kunden.',
        benefit6: 'Globales SaaS',
        benefit6Desc: 'Zugang in 7 Ländern.'
      },
      sidebar: {
        dashboard: 'Dashboard',
        analytics: 'Analysen PRO',
        newBudget: 'Neues Angebot',
        settings: 'Einstellungen',
        subscription: 'Abonnement',
        logout: 'Abmelden'
      },
      dashboard: {
        totalPaid: 'Gesamt Erhalten',
        approvedVal: 'Bestätigt',
        pendingVal: 'Ausstehend',
        tableRef: 'Referenz / Kunde',
        activeSpecialties: 'Aktive Spezialgebiete',
        specialtiesSub: 'Bereiche, in denen Ihr Unternehmen tätig ist.',
        recentActivity: 'Letzte Aktivitäten',
        noBudgets: 'Noch keine Angebote erstellt.',
        createFirst: 'Erstellen Sie jetzt Ihr erstes professionelles Angebot.'
      },
      analytics: {
        title: 'Business-Analysen PRO',
        subtitle: 'Verwandeln Sie Angebote in wertvolle Daten.',
        upgradeBtn: 'AUF PREMIUM UPGRADEN',
        revenueApproved: 'Bestätigter Umsatz',
        pipelinePending: 'Pipeline Offen',
        conversionRate: 'Konversionsrate',
        distributionStatus: 'Verteilung nach Status',
        revenueBySpecialty: 'Wert nach Spezialgebiet',
        note: 'Diese Analysen berücksichtigen alle historischen Angebote.',
        benefit1Title: 'Verteilung',
        benefit1Desc: 'Status Ihrer Projekte.',
        benefit2Title: 'Umsatz nach Kategorie',
        benefit2Desc: 'Rentable Dienstleistungen.',
        benefit3Title: 'Bestätigung',
        benefit3Desc: 'Effektivität der Angebote.'
      },
      subscription: {
        currentPlan: 'Aktueller Plan',
        renewsOn: 'Abo verlängert sich am',
        upgradeBtn: 'Upgrade auf Premium',
        plansTitle: 'Verfügbare Pläne',
        historyTitle: 'Verlauf und Rechnungen',
        paymentMethod: 'Zahlungsmethode',
        basicName: 'Basis',
        proName: 'Professionell',
        freePrice: '0€/Monat',
        proPrice: '9,90€/Monat',
        proTaxInfo: '+ MwSt (Gesamt 12,18€)',
        activePlan: 'Aktiver Plan',
        selectPlan: 'Plan wählen',
        emptyHistory: 'Keine Rechnungshistorie',
        emptyHistoryDesc: 'Upgrade für automatische Rechnungen.',
        changeMethod: 'Ändern',
        checkoutTitle: 'ÁTRIO Premium Checkout',
        processing: 'Zahlung wird verarbeitet...',
        payNow: 'Jetzt bezahlen',
        features: {
          budgets3: '3 Angebote monatlich',
          budgetsInf: 'Unbegrenzte Angebote',
          pdfExport: 'Prof. PDF-Export',
          payments: 'Zahlungsverwaltung',
          analytics: 'Finanzanalysen PRO'
        }
      },
      editor: {
        clientTitle: 'Kundeninformationen',
        itemsTitle: 'Leistungspositionen',
        totalsTitle: 'Summen und Steuern',
        validUntil: 'Gültigkeit des Angebots',
        notes: 'Angebotsnotizen',
        paymentTerms: 'Lokale Zahlungsbedingungen angewendet.'
      },
      specialtyNames: {
        [Specialty.Pedreiro]: 'Maurer',
        [Specialty.Canalizador]: 'Installateur',
        [Specialty.Eletricista]: 'Elektriker',
        [Specialty.Pladur]: 'Trockenbau',
        [Specialty.Capoto]: 'Wärmedämmung',
        [Specialty.Pintura]: 'Maler',
        [Specialty.Carpinteiro]: 'Zimmermann',
        [Specialty.Estuque]: 'Stuckateur',
        [Specialty.Outro]: 'Sonstiges'
      }
    }
  },
  CH: {
    name: 'Suíça',
    flag: '🇨🇭',
    currency: 'CHF',
    locale: 'de-CH',
    taxLabels: { vat: 'MwSt', income: 'Kantonssteuer', social: 'AVS', idNumber: 'UID' },
    defaultRates: { vat: 8.1, income: 20, social: 10 },
    translations: {
      ...COMMON_PT,
      save: 'Speichern',
      cancel: 'Abbrechen',
      export: 'PDF Exportieren',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      add: 'Hinzufügen',
      back: 'Zurück',
      next: 'Weiter',
      finish: 'Fertigstellen',
      loading: 'Laden...',
      confirm: 'Bestätigen',
      status: 'Angebotsstatus',
      date: 'Datum',
      total: 'Gesamt',
      action: 'Ação',
      name: 'Name',
      email: 'E-Mail',
      phone: 'Telefon',
      address: 'Adresse',
      nif: 'UID',
      contactPerson: 'Kontaktperson',
      password: 'Passwort',
      companyName: 'Firmenname',
      specialties: 'Spezialgebiete',
      description: 'Beschreibung',
      quantity: 'Menge',
      unit: 'Einh.',
      price: 'Preis',
      subtotal: 'Zwischensumme',
      balance: 'Offener Saldo',
      paid: 'Bezahlt',
      pending: 'Pendent',
      approved: 'Genehmigt',
      rejected: 'Abgelehnt',
      draft: 'Pendent',
      renewalAlert: 'Ihr monatliches Abonnement läuft in {days} Tagen ab. Jetzt verlängern, um Dienstunterbrechungen zu vermeiden!',
      hub: {
        summary: 'Übersicht',
        info: 'Angebot',
        payments: 'Zahlungen',
        expenses: 'Projektkosten',
        back: 'Zurück',
        welcome: 'Willkommen bei Átrio',
        loadingEnv: 'Ihr Arbeitsbereich wird geladen...',
        configuring: 'Ihr professionelles Portal wird konfiguriert...'
      },
      auth: {
        loginTitle: 'Login',
        loginSub: 'Greifen Sie auf Ihr Dashboard zu.',
        registerTitle: 'SaaS-Konto eröffnen',
        registerSub: 'Schweizer Qualität in der Verwaltung.',
        verifyTitle: 'Code gesendet',
        verifySub: 'E-Mail prüfen.',
        btnEnter: 'Login',
        btnRegister: 'Konto erstellen',
        btnVerify: 'Aktivieren',
        switchRegister: 'Neu? Konto erstellen',
        switchLogin: 'Bereits membro? Login',
        benefit1: 'Strukturierte PDFs',
        benefit1Desc: 'Schweizer Standard Export.',
        benefit2: 'Finanzberichte',
        benefit2Desc: 'Volle Transparenz.',
        benefit3: 'Zahlungskontrolle',
        benefit3Desc: 'Effizientes Mahnwesen.',
        benefit4: 'CH-Steuersätze',
        benefit4Desc: 'MwSt 8.1% integriert.',
        benefit5: 'Kundenstamm',
        benefit5Desc: 'CRM inklusive.',
        benefit6: 'SaaS Global',
        benefit6Desc: 'Grenzüberschreitend bereit.'
      },
      sidebar: {
        dashboard: 'Dashboard',
        analytics: 'Analysen PRO',
        newBudget: 'Neues Angebot',
        settings: 'Einstellungen',
        subscription: 'Abo',
        logout: 'Abmelden'
      },
      dashboard: {
        totalPaid: 'Zahlungseingänge',
        approvedVal: 'Genehmigt',
        pendingVal: 'Pendent',
        tableRef: 'Ref / Kunde',
        activeSpecialties: 'Spezialgebiete',
        specialtiesSub: 'Tätigkeitsbereiche Ihrer Firma.',
        recentActivity: 'Aktivitäten',
        noBudgets: 'Noch keine Angebote.',
        createFirst: 'Erstellen Sie Ihr erstes Angebot.'
      },
      analytics: {
        title: 'Business-Analysen PRO',
        subtitle: 'Verwandeln Sie Angebote in Daten.',
        upgradeBtn: 'PREMIUM FREISCHALTEN',
        revenueApproved: 'Genehmigter Umsatz',
        pipelinePending: 'Pendente Pipeline',
        conversionRate: 'Erfolgsquote',
        distributionStatus: 'Verteilung Status',
        revenueBySpecialty: 'Wert pro Sparte',
        note: 'Analysen basieren auf allen Angeboten da Firma.',
        benefit1Title: 'Status',
        benefit1Desc: 'Überblick Projekte.',
        benefit2Title: 'Umsatz Sparten',
        benefit2Desc: 'Lukrative Services.',
        benefit3Title: 'Erfolg',
        benefit3Desc: 'Angebotsqualität.'
      },
      subscription: {
        currentPlan: 'Aktueller Status',
        renewsOn: 'Erneuerung am',
        upgradeBtn: 'Premium-Abo lösen',
        plansTitle: 'Abo-Optionen',
        historyTitle: 'Rechnungen',
        paymentMethod: 'Zahlung',
        basicName: 'Free',
        proName: 'Business',
        freePrice: '0 CHF/Monat',
        proPrice: '9,90 CHF/Monat',
        proTaxInfo: '+ MwSt (Exkl.)',
        activePlan: 'Status: Aktiv',
        selectPlan: 'Plan wählen',
        emptyHistory: 'Keine Rechnungen',
        emptyHistoryDesc: 'Business-Abo für Belege.',
        changeMethod: 'Ändern',
        checkoutTitle: 'Checkout ÁTRIO',
        processing: 'Verarbeitung...',
        payNow: 'Bezahlen',
        features: {
          budgets3: '3 Angebote/Monat',
          budgetsInf: 'Unlimitiert',
          pdfExport: 'Prof. Export',
          payments: 'Debitor-Management',
          analytics: 'Business-Reporting'
        }
      },
      editor: {
        clientTitle: 'Kundendaten',
        itemsTitle: 'Posten',
        totalsTitle: 'Total & Steuern',
        validUntil: 'Gültigkeit des Angebots',
        notes: 'Bemerkungen',
        paymentTerms: 'Schweizer Zahlungsfristen gelten.'
      },
      specialtyNames: {
        [Specialty.Pedreiro]: 'Maurer',
        [Specialty.Canalizador]: 'Sanitär',
        [Specialty.Eletricista]: 'Elektriker',
        [Specialty.Pladur]: 'Gipser',
        [Specialty.Capoto]: 'Isolation',
        [Specialty.Pintura]: 'Maler',
        [Specialty.Carpinteiro]: 'Schreiner',
        [Specialty.Estuque]: 'Verputzer',
        [Specialty.Outro]: 'Anderes'
      }
    }
  },
  IT: {
    name: 'Itália',
    flag: '🇮🇹',
    currency: 'EUR',
    locale: 'it-IT',
    taxLabels: { vat: 'IVA', income: 'IRPEF', social: 'INPS', idNumber: 'P.IVA/CF' },
    defaultRates: { vat: 22, income: 23, social: 26 },
    translations: {
      ...COMMON_PT,
      save: 'Salva Modifiche',
      cancel: 'Annulla',
      export: 'Esporta PDF',
      delete: 'Elimina',
      edit: 'Modifica',
      add: 'Aggiungi',
      back: 'Indietro',
      next: 'Avanti',
      finish: 'Concludi',
      loading: 'Caricamento...',
      confirm: 'Conferma',
      status: 'Stato del Preventivo',
      date: 'Data',
      total: 'Totale',
      action: 'Ação',
      name: 'Nome',
      email: 'Email',
      phone: 'Telefono',
      address: 'Indirizzo',
      nif: 'P.IVA',
      contactPerson: 'Referente',
      password: 'Password',
      companyName: 'Nome Azienda',
      specialties: 'Specialità',
      description: 'Descrição',
      quantity: 'Qtà',
      unit: 'Un.',
      price: 'Prezzo',
      subtotal: 'Subtotale',
      balance: 'Saldo Aperto',
      paid: 'Pagato',
      pending: 'In Attesa',
      approved: 'Approvato',
      rejected: 'Rifiutato',
      draft: 'In Attesa',
      renewalAlert: 'Il tuo abbonamento mensile scade tra {days} giorni. Rinnova ora per evitare l\'interruzione dei tuoi servizi!',
      hub: {
        summary: 'Riassunto',
        info: 'Preventivo',
        payments: 'Pagamenti',
        expenses: 'Costi di Lavoro',
        back: 'Indietro',
        welcome: 'Benvenuti ad Átrio',
        loadingEnv: 'Caricamento del tuo ambiente...',
        configuring: 'Configurazione del portale professionale...'
      },
      auth: {
        loginTitle: 'Accedi',
        loginSub: 'Accedi al tuo pannello ÁTRIO.',
        registerTitle: 'Crea account SaaS',
        registerSub: 'Unisciti a centinaia di aziende.',
        verifyTitle: 'Codice Inviato',
        verifySub: 'Controlla la tua email.',
        btnEnter: 'Accedi Ora',
        btnRegister: 'Criar Plataforma',
        btnVerify: 'Ativa Account',
        switchRegister: 'Nuovo? Crea account',
        switchLogin: 'Già registrato? Accedi',
        benefit1: 'PDF Strutturati',
        benefit1Desc: 'Esportazione professionale in 1 clic.',
        benefit2: 'Report PRO',
        benefit2Desc: 'Analisi profitto e conversione.',
        benefit3: 'Gestione Finanziaria',
        benefit3Desc: 'Controllo totale pagamenti.',
        benefit4: 'Tasse Automatiche',
        benefit4Desc: 'Fiscalità locale adaptada.',
        benefit5: 'Storico Centrale',
        benefit5Desc: 'CRM integrado per i clientes.',
        benefit6: 'SaaS Globale',
        benefit6Desc: 'Accesso in 7 paesi.'
      },
      sidebar: {
        dashboard: 'Cruscotto',
        analytics: 'Analisi PRO',
        newBudget: 'Nuovo Preventivo',
        settings: 'Impostazioni',
        subscription: 'Abbonamento',
        logout: 'Esci'
      },
      dashboard: {
        totalPaid: 'Totale Incassato',
        approvedVal: 'Approvati',
        pendingVal: 'In Attesa',
        tableRef: 'Riferimento / Cliente',
        activeSpecialties: 'Specialità Ative',
        specialtiesSub: 'Settori in cui opera la tua azienda.',
        recentActivity: 'Atividade Recente',
        noBudgets: 'Nessun preventivo creato.',
        createFirst: 'Crea ora il teu primeiro preventivo professionale.'
      },
      analytics: {
        title: 'Analisi Business PRO',
        subtitle: 'Trasforma i preventivi in dati di valore.',
        upgradeBtn: 'PASSA A PREMIUM',
        revenueApproved: 'Entrate Approvate',
        pipelinePending: 'Pipeline Pendente',
        conversionRate: 'Taso Conversione',
        distributionStatus: 'Stato Preventivi',
        revenueBySpecialty: 'Valore per Categoria',
        note: 'Le analisi considerano tutti i preventivi storici.',
        benefit1Title: 'Stato',
        benefit1Desc: 'Panoramica progetti.',
        benefit2Title: 'Entrate Categoria',
        benefit2Desc: 'Servizi più redditizi.',
        benefit3Title: 'Successo',
        benefit3Desc: 'Efficacia propostas.'
      },
      subscription: {
        currentPlan: 'Piano Attuale',
        renewsOn: 'Abbonamento scade il',
        upgradeBtn: 'Upgrade a Premium',
        plansTitle: 'Piani Disponibili',
        historyTitle: 'Storico Fatture',
        paymentMethod: 'Metodo Pagamento',
        basicName: 'Basico',
        proName: 'Profesional',
        freePrice: '0€/mese',
        proPrice: '9,90€/mese',
        proTaxInfo: '+ IVA (Totale 12,18€)',
        activePlan: 'Piano Ativo',
        selectPlan: 'Seleziona Piano',
        emptyHistory: 'Nessuna fattura',
        emptyHistoryDesc: 'Passa a PRO per receber fatture.',
        changeMethod: 'Modifica',
        checkoutTitle: 'Checkout ÁTRIO',
        processing: 'Elaborazione...',
        payNow: 'Paga Ora',
        features: {
          budgets3: '3 Preventivi/Mese',
          budgetsInf: 'Illimitati',
          pdfExport: 'Export PDF Prof.',
          payments: 'Gestione Incassi',
          analytics: 'Analisi Business'
        }
      },
      editor: {
        clientTitle: 'Dati Cliente',
        itemsTitle: 'Voci di Spesa',
        totalsTitle: 'Totali e Tasse',
        validUntil: 'Validità del preventivo',
        notes: 'Note Preventivo',
        paymentTerms: 'Condizioni de pagamento locais applicate.'
      },
      specialtyNames: {
        [Specialty.Pedreiro]: 'Muratore',
        [Specialty.Canalizador]: 'Idraulico',
        [Specialty.Eletricista]: 'Elettricista',
        [Specialty.Pladur]: 'Cartongesso',
        [Specialty.Capoto]: 'Cappotto',
        [Specialty.Pintura]: 'Imbianchino',
        [Specialty.Carpinteiro]: 'Falegname',
        [Specialty.Estuque]: 'Stuccatore',
        [Specialty.Outro]: 'Altro'
      }
    }
  },
  US: {
    name: 'EUA',
    flag: '🇺🇸',
    currency: 'USD',
    locale: 'en-US',
    taxLabels: { vat: 'Sales Tax', income: 'Federal Tax', social: 'Social Security', idNumber: 'EIN/SSN' },
    defaultRates: { vat: 7, income: 20, social: 6.2 },
    translations: {
      ...COMMON_PT,
      save: 'Save Changes',
      cancel: 'Cancel',
      export: 'Export PDF',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      back: 'Back',
      next: 'Next',
      finish: 'Finish',
      loading: 'Loading...',
      confirm: 'Confirm',
      status: 'Estimate Status',
      date: 'Date',
      total: 'Total',
      action: 'Action',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      nif: 'EIN/SSN',
      contactPerson: 'Contact Person',
      password: 'Password',
      companyName: 'Company Name',
      specialties: 'Services',
      description: 'Description',
      quantity: 'Qty',
      unit: 'Unit',
      price: 'Price',
      subtotal: 'Subtotal',
      balance: 'Open Balance',
      paid: 'Paid',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      draft: 'Pending',
      renewalAlert: 'Your monthly subscription expires in {days} days. Renew now to avoid service interruption!',
      hub: {
        summary: 'Summary',
        info: 'Estimate',
        payments: 'Payments',
        expenses: 'Job Costs',
        back: 'Back',
        welcome: 'Welcome to Átrio',
        loadingEnv: 'Loading your environment...',
        configuring: 'Configuring your professional portal...'
      },
      auth: {
        loginTitle: 'Sign In',
        loginSub: 'Access your ÁTRIO dashboard.',
        registerTitle: 'Create SaaS Account',
        registerSub: 'Join hundreds of construction firms.',
        verifyTitle: 'Code Sent',
        verifySub: 'Check your email inbox.',
        btnEnter: 'Sign In Now',
        btnRegister: 'Criar Plataforma',
        btnVerify: 'Verify Account',
        switchRegister: 'New? Create an account',
        switchLogin: 'Already have access? Sign in',
        benefit1: 'Structured PDFs',
        benefit1Desc: 'Professional 1-click export.',
        benefit2: 'PRO Analytics',
        benefit2Desc: 'Profit and conversion tracking.',
        benefit3: 'Financial Control',
        benefit3Desc: 'Manage payments efficiently.',
        benefit4: 'Auto Tax Rates',
        benefit4Desc: 'Local taxes pre-configured.',
        benefit5: 'Central CRM',
        benefit5Desc: 'Track all customer history.',
        benefit6: 'Global SaaS',
        benefit6Desc: 'Ready for 7 countries.'
      },
      sidebar: {
        dashboard: 'Dashboard',
        analytics: 'Analytics PRO',
        newBudget: 'New Estimate',
        settings: 'Settings',
        subscription: 'Subscription',
        logout: 'Sign Out'
      },
      dashboard: {
        totalPaid: 'Total Received',
        approvedVal: 'Approved',
        pendingVal: 'Pending',
        tableRef: 'Ref / Client',
        activeSpecialties: 'Active Specialties',
        specialtiesSub: 'Sectors your company is active in.',
        recentActivity: 'Recent Activity',
        noBudgets: 'No estimates yet.',
        createFirst: 'Create your first professional estimate now.'
      },
      analytics: {
        title: 'Business Analytics PRO',
        subtitle: 'Turn estimates into actionable insights.',
        upgradeBtn: 'UPGRADE TO PREMIUM',
        revenueApproved: 'Approved Revenue',
        pipelinePending: 'Pending Pipeline',
        conversionRate: 'Conversion Rate',
        distributionStatus: 'Status Distribution',
        revenueBySpecialty: 'Revenue by Service',
        note: 'These analytics are based on all historical estimates.',
        benefit1Title: 'Distribution',
        benefit1Desc: 'Project status overview.',
        benefit2Title: 'Service Revenue',
        benefit2Desc: 'Most profitable sectors.',
        benefit3Title: 'Success',
        benefit3Desc: 'Proposal effectiveness.'
      },
      subscription: {
        currentPlan: 'Current Plan',
        renewsOn: 'Next billing date',
        upgradeBtn: 'Upgrade to Premium',
        plansTitle: 'Available Plans',
        historyTitle: 'Billing & History',
        paymentMethod: 'Payment Method',
        basicName: 'Starter',
        proName: 'Professional',
        freePrice: '$0/mo',
        proPrice: '$9.90/mo',
        proTaxInfo: '+ Local Taxes',
        activePlan: 'Active Plan',
        selectPlan: 'Choose Plan',
        emptyHistory: 'No billing history',
        emptyHistoryDesc: 'Upgrade to PRO to see invoices.',
        changeMethod: 'Edit',
        checkoutTitle: 'ÁTRIO Premium Checkout',
        processing: 'Processing...',
        payNow: 'Pay Now',
        features: {
          budgets3: '3 Estimates/Month',
          budgetsInf: 'Unlimited Estimates',
          pdfExport: 'Prof. PDF Export',
          payments: 'Payment Tracking',
          analytics: 'Business Analytics'
        }
      },
      editor: {
        clientTitle: 'Client Details',
        itemsTitle: 'Line Items',
        totalsTitle: 'Totals & Taxes',
        validUntil: 'Estimate Validity',
        notes: 'Estimate Notes',
        paymentTerms: 'Local payment terms applied.'
      },
      specialtyNames: {
        [Specialty.Pedreiro]: 'Bricklayer',
        [Specialty.Canalizador]: 'Plumber',
        [Specialty.Eletricista]: 'Electrician',
        [Specialty.Pladur]: 'Drywaller',
        [Specialty.Capoto]: 'Insulator',
        [Specialty.Pintura]: 'Painter',
        [Specialty.Carpinteiro]: 'Carpenter',
        [Specialty.Estuque]: 'Plasterer',
        [Specialty.Outro]: 'Other'
      }
    }
  }
};

export const INITIAL_COMPANIES: Company[] = [];

export const SPECIALTY_COLORS: Record<Specialty, string> = {
  [Specialty.Pedreiro]: 'bg-amber-100 text-amber-700 border-amber-200',
  [Specialty.Canalizador]: 'bg-blue-100 text-blue-700 border-blue-200',
  [Specialty.Eletricista]: 'bg-yellow-100 text-yellow-700 border-yellow-200',
  [Specialty.Pladur]: 'bg-slate-100 text-slate-700 border-slate-200',
  [Specialty.Capoto]: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  [Specialty.Pintura]: 'bg-purple-100 text-purple-700 border-purple-200',
  [Specialty.Carpinteiro]: 'bg-orange-100 text-orange-700 border-orange-200',
  [Specialty.Estuque]: 'bg-stone-100 text-stone-700 border-stone-200',
  [Specialty.Outro]: 'bg-gray-100 text-gray-700 border-gray-200',
};
